server:
  error:
    include-message: always
  port: 8081

application:
  issue:
    max-allowed-books: 3

spring:
  datasource:
    url: jdbc:mysql://logistde.beget.tech:3306/logistde_db_jpa
    username: logistde_db_jpa
    password: TestWork_123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update